### ISSUE TITLE
debugging nginx error

### ISSUE THREAD

**Issue by mttjohnson** [davidalger/devenv#26]
While debugging worked in PhpStorm, I ran into an issue where nginx decided it had waiting long enough and rendered an error on the page while I had the PhpStorm debugging session paused.

It looks like nginx is waiting about 60 seconds and then gives up, so if you haven't finished your debugging within 60 seconds nginx takes over and throws an error on the page.

**Comment by davidalger** [comment]
@ericthehacker / @mttjohnson what would either of you consider a reasonable timeout for the proxy_pass? I'm not sure it makes sense to have no timeout, otherwise nginx will simply wait forever if apache dies and never replies, but given this is for development we need it to be reasonably high enough to facilitate these long-running debug requests. Does 10 minutes sound reasonable?

**Comment by mttjohnson** [comment]
I'm going to say that 10-15 minutes seems like a reasonable default. I'll likely set mine to 30 minutes just so that I can have it hang on for the occasional longer debugging sessions, though most probably won't hit 10 minutes.

**Comment by ericthehacker** [comment]
@davidalger @mttjohnson 
I think the 600 second timeout in #27 is perfect.
