### ISSUE TITLE
Increase PHP memory_limit to prevent Magento 2 CE installs from failing

### ISSUE THREAD

**Issue by erikhansen** [davidalger/devenv#72]
In the past day, both myself and @ntoombs19 have experienced an issue where installing Magento 2 CE using m2setup.sh has resulted in an error like this:

```bash
$ m2setup.sh -d -v --hostname=example.dev
==> Creating directory /server/sites/turntoce.dev/
==> Installing magento meta-packages
Installing magento/project-community-edition (2.0.6)
  - Installing magento/project-community-edition (2.0.6)
    Downloading: 100%         

Created project in /server/sites/turntoce.dev/
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing magento/magento-composer-installer (0.1.8)
    Loading from cache
…
…
…
…
  - Installing composer/composer (1.0.0-alpha10)
    Loading from cache
The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:940
```

Increasing the `memory_limit` to `1536M` in the `/etc/php.d/00-php.ini` file fixes the problem, although I'm not specifically recommending that value.

**Comment by erikhansen** [comment]
Actually, even increasing the `memory_limit` to `2GB` still results issues if you install sample data at the same time:

```
$ m2setup.sh -d -v --hostname=example.dev
==> Creating directory /server/sites/turntoce.dev/
==> Installing magento meta-packages
Installing magento/project-community-edition (2.0.6)
  - Installing magento/project-community-edition (2.0.6)
    Downloading: 100%         

Created project in /server/sites/turntoce.dev/
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing magento/magento-composer-installer (0.1.8)
    Loading from cache
…
…
…
…
  - Installing magento/module-catalog-sample-data (100.0.5)
    Loading from cache

  - Installing magento/module-bundle-sample-data (100.0.5)
    Loading from cache
The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details


                                                     
  [ErrorException]                                   
  proc_open(): fork failed - Cannot allocate memory  
```

Since the virtual machine is set to 2GB of RAM, I'm not able to test increasing the `memory_limit` to greater than `2GB`. However at this point, it is probably better to look into configuring the Composer swap, as it mentions in the error log.

**Comment by mttjohnson** [comment]
Rob was running into some issues with hitting the memory limit while using composer to install OroCRM. Other than that, this is the first issue I've heard of relating to hitting the 1GB memory limit not being sufficient. It seems ridiculous to me that it would need more than 1GB RAM to install things. I expect there may be some other underlying issue at hand, but I'm not sure how to isolate and identify it.

**Comment by davidalger** [comment]
Do any of y'all know if these memory limits are run into when running composer with xdebug disabled? I know xdebug kills the tools performance (and it will sometimes tell you this). It'd be worth checking.

The proc_open error is actually because the virtual machine does not have any allocated RAM left-over to allocate, kind of like the message indicates when it says the swap hasn't been configured. The web VMs have been configured with 2GB of RAM, which is typically enough, but won't be enough to handle various web requests simultaneously to memory hungry CLI operations such as the sample data install. I've run into the same issues on small DO servers. We could definitely bump it up a bit, but it gets potentially ugly because if the db vm has 4 GB and the web VM has 2, that leaves 2 GB on an 8 GB host machine. Bumping it up to 4 GB would allow the two VMs to use all the RAM on an 8 GB machine. How much of an impact would it have exactly? I don't know… :)

-- 
David Alger
Director of Technology, Classy Llama

**Comment by erikhansen** [comment]
Running `m2setup.sh -d -v --hostname=memorylimittest.dev` now with xdebug disabled and will let you know what happens.

**Comment by erikhansen** [comment]
I've not been able to reproduce the issue. I tried clearing the Composer cache, dropping the memory limit back down to 1GB, ensuring that xdebug was enabled, and doing an M2 CE install with sample data, but the issue has not surfaced again. Closing this task until and unless I or someone else runs into this again in a consistent way.
