### ISSUE TITLE
Make vhost.sh wrapper execute vhost.sh on all active web nodes rather than just the default

### ISSUE THREAD

**Issue by ntoombs19** [davidalger/devenv#81]
I'm working on a site from a web70 server and vhost.sh failed to include the config for the site running on the web70 node since it the web70 node was not the default. It would be nice if the wrapper ran vhost.sh on all active web nodes rather than just the default web node.

**Comment by mttjohnson** [comment]
If the wrapper was running from the host to reset the configs it would be ideal to have something check to see which web nodes were running, and then pass the calls to each of the web nodes. Granted that would require more work to make the wrapper be smart when run from the host. 

I believe the plan is to move away from multiple web nodes and allow a single web node be able to run different sites with different versions of php if needed using PHP-FPM. With that on the road map, I doubt we'd want to make the vhosts.sh script smarter since in the near future it may not be necessary.

My suggestion would be to practice being a bit more explicit and more intentional with the commands and always specify a host when and avoid using the commands that use a default like `vcd` or `vhosts.sh`. Login to the web node specifically `vagrant ssh web70` and run commands from within the VM.

**Comment by erikhansen** [comment]
@mttjohnson I recently documented the project setup instructions for a new M2 build, but failed to take into account the problem Nathan mentioned. I think that is what prompted this issue being created. I've updated the readme accordingly: https://bitbucket.org/classyllama/azisupply-com#markdown-header-update-vhost-configuration

**Comment by davidalger** [comment]
Closing this one out as the vhosts.sh will be removed from the scripts list directly available on the host machine. This change has already been made in develop via commit 342a6f2.

The command will continue to be able to be run via the host machine via the vcd command:

* vcd vhosts.sh — runs on default vm
* vcd web56 vhosts.sh

This will be available as soon as develop is merged into the mainline.
